mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name="mysite"

urlpatterns = [
    path("", views.landing_page, name="thesis_landing_page"),
    path("thesis/", include("thesis.urls")),
    path("admin/", admin.site.urls, name="admin"),
]

thesis/urls.py
from django.urls import path
from . import views

app_name = "thesis"
urlpatterns = [
    path("", views.thesis_list, name="thesis_list"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.thesis_details,
        name="thesis_details",
    ),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path("comment/", views.thesis_search, name="thesis_search")
]

thesis/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager


# Create your models here.
class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    the_one_who_posted = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="capstone_posts"
    )
    abstract = models.TextField()

    authors = models.CharField(max_length=500)
    adviser = models.CharField(max_length=250)
    panels = models.CharField(max_length=500)

    status = models.CharField(
        max_length=3, choices=Status.choices, default=Status.DRAFT
    )

    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    tags = TaggableManager()

    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"]),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            "thesis:thesis_details",
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug],
        )
class Comment(models.Model):
    post = models.ForeignKey(Post, 
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email=models.EmailField()
    body= models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated= models.DateTimeField(auto_now=True)
    active=models.BooleanField(default=True)

    class Meta:
        ordering=['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

thesis/forms.py
from django.forms import ModelForm
from .models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "body"]

mysite/views.py
from django.shortcuts import render
def landing_page(request):
    return render(
        request,
        "home.html",
    )

thesis/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from .forms import CommentForm
from django.views.decorators.http import require_POST



def thesis_search(request):
    keyword = request.GET.get("keyword")
    post = Post.objects.filter(
        Q(title__contains=keyword)
        | Q(authors__contains=keyword)
        | Q(abstract__contains=keyword)
    )
    paginator = Paginator(post, 3)
    page_number = request.GET.get("page")
    try:
        post = paginator.page(page_number) 
    except PageNotAnInteger:
        post = paginator.page(1)
    except EmptyPage:
        post = paginator.page(paginator.num_pages)
    return render(request, "thesis/pagination.html", {"post": post})

def thesis_list(request):
    post = Post.objects.all()
    paginator = Paginator(post, 3)
    page_number = request.GET.get("page")
    try:
        post = paginator.page(page_number) 
    except PageNotAnInteger:
        post = paginator.page(1)
    except EmptyPage:
        post = paginator.page(paginator.num_pages)
    return render(request, "thesis/pagination.html", {"post": post})


def thesis_details(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        publish__year=year,
        publish__month=month,
        publish__day=day,
        slug=post,
    )
    comments = post.comments.filter(active=True)
    form = CommentForm()

    return render(request, "thesis/post/detail.html", {"post": post,"comments": comments,
                   "form":form})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

    return render(request, "thesis/post/comment.html",
                        {'post': post,
                         'form': form, 
                         'comment': comment})

mysite/templates/home.html
<!-- book_list.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static "blog/css/style.css" %}" />
    <title>Thesis Titles</title>
  </head>
  <body>
    <div>
      <div>Thesis Title Searcher</div>
      <div>
        <form>
          <input type="text" placeholder="Search a title here.." />
          <button type="submit">Search</button>
        </form>
      </div>
      <a href="/thesis">View Recent Titles</a>
    </div>
  </body>
</html>

thesis/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock%}</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>
<body>
  {% include "thesis/post/includes/search_form.html" %}
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <div id="sidebar">
    <h2>My Blog</h2>
    <p>this is my blog</p>
  </div>
</body>
</html>

thesis/templates/home.html
<!-- book_list.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static "blog/css/style.css" %}" />
    <title>Thesis Titles</title>
  </head>
  <body>
    <div>
      <div>Thesis Title Searcher</div>
      <div>
        <form>
          <input type="text" placeholder="Search a title here.." />
          <button type="submit">Search</button>
        </form>
      </div>
      <a href="/thesis/?page=1">View Recent Titles</a>
    </div>
  </body>
</html>

thesis/templates/thesis/pagination.html
{% extends "base.html"%} {% block content %}
<div class="container">
  {% for post in post %}
  <div class="item">
    <div class="title">
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </div>
    <div class="publish">{{ post.publish }}</div>
    <div>{{ post.authors }}</div>
    <div>{{post.abstract}}</div>
  </div>
  {% endfor %}
</div>
<div class="pagination">
  <span class="step-links">
    {% if post.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ post.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ post.number }} of {{ post.paginator.num_pages }}.
    </span>

    {% if post.has_next %}
    <a href="?page={{ post.next_page_number }}">next</a>
    <a href="?page={{ post.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>
{% endblock %}

thesis/templates/thesis/post/comment.html
{% extends "base.html" %}

{% block title %}Add a comment {% endblock%}

{% block content %}
  {% if comment %}
    <h2>Your comment has been added. </h2>
    <p><a href="{{post.get_absolute_url }}">Back to the post</a></p>
  {% else %}
    {% include "thesis/post/includes/comment_form.html" %}
  {% endif %}
  
{% endblock %}

thesis/templates/thesis/post/detail.html
{% extends "base.html" %}
{% block title %}{{post.title}}{% endblock %}

{% block content %}
  <h1>{{post.title}}</h1>
  <p class="date">
  Published {{post.publish}} by {{post.author}}
  </p>
  {{post.body|linebreaks}}
  {% with comments.count as total_comments %}
    <h2>
      {{ total_comments }} comment{{ total_comments|pluralize}}
    </h2>
  {% endwith %}
  {% for comment in comments %}
      <div class="comment">
        <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
        </p>
        {{ comment.body|linebreaks}}
      </div>
    {% empty %}
      <p>There are no comments. </p>
  {% endfor %}
  {% include "thesis/post/includes/comment_form.html" %}
{% endblock %}

thesis/templates/thesis/post/includes/comment_form.html
<h2>Add a new Comment</h2>
<form action="{% url 'thesis:post_comment' post.id %}" method='post'>
  {{ form.as_p }}
  {% csrf_token %}
  <p><input type="submit" value="Add comment"></p>
</form>

thesis/templates/thesis/post/includes/search_form.html
<form action="{% url 'thesis:thesis_search' %}">
    <input type="text" name="keyword" placeholder="Search...">
    <button type="submit">Search</button>
</form>

thesis/templates/thesis_details.html
{% extends "base.html"%} {% block content %}
<div class="title">{{ post.title }}</div>
<div>{{ post.publish }}</div>
<div>{{ post.authors }}</div>
<div>{{post.abstract}}</div>
{% endblock %}